version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: arxiv
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5439:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"    # S3 API
      - "9001:9001"    # Web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  airflow:
    image: apache/airflow:2.8.1-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/arxiv
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__WEBSERVER__SECRET_KEY: "secret"
    depends_on:
      - postgres
    volumes:
      - ./airflow_pipeline:/opt/airflow/dags/airflow_pipeline
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command:  >
      bash -c "airflow db init && airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"

  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work
      - ./scripts:/home/jovyan/scripts
    environment:
      JUPYTER_TOKEN: "letmein"
      GRANT_SUDO: "yes"

volumes:
  pg_data:
  minio_data:
